language: node_js
node_js:
  - "node"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:


install:
  - npm install

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: luncher_back_end
